### ISSUE TITLE
A Describe within a Context within a Describe thinks there's a non-existent test that fails to start

### ISSUE THREAD

**Issue by danger-ranger** [paulcwarren/ginkgo4j#4]
```
  {
    Describe("Subscription Store", () -> {

      Context("with an empty subscriptionStore", () -> {
        Describe("creating a subscription", () -> {
          It("Should be happy and free", () -> assertThat("yes").isEqualTo("yes"));
      });
      });
    });

  }
```

![screen shot 2016-10-21 at 2 53 56 pm](https://cloud.githubusercontent.com/assets/1178694/19608274/3a8a3b8c-979e-11e6-8158-57debc8aa538.png)

**Comment by danger-ranger** [comment]
It seems that ginkgo4j doesn't understand that a `Describe` inside a `Context` is nested within that context. Which makes some sense, but since they're supposed to be functionally equivalent it's probably a bug.

**Comment by paulcwarren** [comment]
Yup, I am sure this is the case.  Just more wanting to get it out there.  Leave it with me and I'll have a fix soonest.

**Comment by danger-ranger** [comment]
Yeah, I'm loving using it. Thanks so much!

**Comment by danger-ranger** [comment]
P.S. This is pretty easy to work around, so no biggie

**Comment by paulcwarren** [comment]
OK.  This was an issue with how I was building the JUnit description model for the test.  Grab 1.0.5 (when it hits maven central in a couple of hours) and give it a go.  Let me know if you have any issues.
