### ISSUE TITLE
Exception in Context -> Tests Ignored

### ISSUE THREAD

**Issue by danger-ranger** [paulcwarren/ginkgo4j#6]
I don't know if this is a valid use case but here goes:

Given:
A context-local variable is defined and assigned in a context block, but not within a beforeEach

When:
The assignment throws an exception, in this case because a field was not set before calling build()

Expected:
All tests in that context block show up as failed or errored

Actual:
No tests in that context block show up at all, in fact the whole file can "go green"

Let me know if you would like an example

**Comment by paulcwarren** [comment]
Hi Gavin,

An example would be helpful.  I have some time next week so I plan on working on these issues.

Thanks
_Paul

**Comment by danger-ranger** [comment]
![screen shot 2017-03-10 at 3 33 29 pm](https://cloud.githubusercontent.com/assets/1178694/23812082/fa06caae-05a6-11e7-9d35-9bf3b4f83b0c.png)
![screen shot 2017-03-10 at 3 33 26 pm](https://cloud.githubusercontent.com/assets/1178694/23812083/fa07b158-05a6-11e7-8a27-4d6fb79af15e.png)

I would expect a failure message, not "No tests were found".


Like I said, not necessarily a valid use case. But there are times when it is tempting to define a variable within a context or describe block, for example to be shared between a ```BeforeEach``` and an ```It``` so that you don't need to make it visible to all other test contexts.

We have avoided this because it's not pretty, but we end up with every variable that isn't local to a single ```It``` or ```BeforeEach``` defined at the class level, which gets cluttered.

**Comment by danger-ranger** [comment]
An example of the situation that we would like to avoid but can't really. Mostly because java forbids non-final (or effectively final) variables to be defined within a lambda.
![screen shot 2017-03-10 at 3 40 57 pm](https://cloud.githubusercontent.com/assets/1178694/23812310/076a9a94-05a8-11e7-8991-c502bb201d02.png)

**Comment by paulcwarren** [comment]
Fixed in 1.0.8
